export enum EnvKeys {
  HTTP_PORT = 'HTTP_PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  JWT_SECRET = 'JWT_SECRET',
  JWT_SECRET_REFRESH = 'JWT_SECRET_REFRESH',
}
